### ISSUE TITLE
[BUG]: Current card implementation shuffle items only on card creation

### ISSUE THREAD

**Issue by vvscode** [memory-cards/card-types#4]
The idea was
> Shuffle all elements to change an order for each interaction

The current implementation is buggy - it shuffles options only once, on card export. 

**Expected behavior:** order of items should renew on each card open

**Comment by vvscode** [comment]
@zenby @Citrinin are we going fix the same for `order_items` ? ))

**Comment by zenby** [comment]
@vvscode we've done it already [here ](https://github.com/memory-cards/card-types/pull/12/files)
(I've changed the name of the PR because it was incorrect.)
